import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://cdnbatera.bateraclube.com.br/files/122/MED_bateria-pearl-export-exx-series-mahogany-jet-black-2210121416-ferragens-8302196..jpg",
    title: "Bateria Pearl Export Exx ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$5.000",
    newPrice: "$4.200",
    company: "Pearl",
    color: "black",
    category: "bateria",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSVYhVpXZtvNe5R58vvNM4rA7jiCLcKXZMljhNF8YfELPCmXYKzuUx6kaQdSD4poixS-CVX4oxtIqkCTE64mLnWKFiT8hi_Tm5wx0FKZ9_Rhh7yNbkjMg31&usqp=CAE",
    title: "Bateria Odery inRock 22 ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$5.000",
    newPrice: "$4.000",
    company: "Odery",
    color: "green",
    category: "bateria",
  },

  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR4jYOmyeVCBW8rVuAJBx9X2yDdNBxO6otEBxMSk6QhEuJacUXSIUa76mP1zQk46TS-adB8eXagJ4rqdI7A1k6D_XUvKeXA32Fcw9pvLjs&usqp=CAE",
    title: "Bateria Tama Super Star",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$3,000",
    newPrice: "$2.500",
    company: "Tama",
    color: "white",
    category: "bateria",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTR2Wv3XEg0NK6jPpmNaSU10poAFdPwWrI6CKCeCM5ltn2V4fU3fWhJ4nJuwNZeLxmYNAdyxT6l12YJADBljX9TGCe4QSoI2hzsRD7YfU8iwgOXaIWgQtjz&usqp=CAE",
    title: "Bateria Nagano Garage",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$2.500",
    newPrice: "$2.000",
    company: "Nagano",
    color: "red",
    category: "bateria",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ3I2GmDAqxK1RXUwpr3-qq-NoTy3z1Ge2kCZtFAcRa5nCM4WjDMYBgmslTYdHthomrhVF2d2wvzdM90CAd-Np8g0CsvL-YJc9qJEkMC1EGTuzG3n3gmHTP&usqp=CAE",
    title: "Bateria D`One ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$3.000",
    newPrice: "2.000",
    company: "D`One",
    color: "blue",
    category: "bateria",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQzWWPtyJjPxXjknF-hcfk7ipBwIHkkYAtC5TWVKy_VTA6pMpRVFaInG6_LICoURVJqOHvS1rkPeR3Wi92FdqyvPth1HjbsLYCD5tgNPus&usqp=CAE",
    title: "Guitarra Fender",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Fender",
    color: "green",
    category: "guitarra",
  },

  {
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSPUkCzqQ-UB51kXxpSHXNwWNTBxbAdXTp1QIHg3FkrG5Ok-6DOZSxsPfTqApBz-HeNTT3GdyM-e9X7xoQnefmZoV4LUS9bv8b8AnwwUNk9n7QDgNo_5mXN&usqp=CAE",
    title: "Tagima Telecaster T-910",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$3.000",
    newPrice: "$2.500",
    company: "Tagima",
    color: "black",
    category: "guitarra",
  },

  {
    img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRIBM-lOKZzPSRnt-_MMd8ySUkg9nXCCILpfHR2FJ50AJ-7hlfRie23prR4nK7a0HOI5p4U9Exhbf5zDbTCoq7EHfByjA9fS785kh5S5pWuxvDwn6e58R0o&usqp=CAE",
    title: "Gibson Les Paul",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$40.000",
    newPrice: "$17.000",
    company: "Gibson",
    color: "red",
    category: "guitarra",
  },

  {
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlqHI5zZVmvo7m1WQPFzK5VwFO_X5QjfssoIjnjOiVQ4PA2x9eNtx6fpneUdak3IiiFP-GjLNtmoyoH3XqMs9g0b7xnOai5Trgp-7itinsPqgMZKFPhHsP&usqp=CAE",
    title: "Ibanez Semiacùstica",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$5.000",
    newPrice: "$4.000",
    company: "Ibanez",
    color: "white",
    category: "",
  },

  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTQFZ0_UBpSctQEzakmIr1N-dNmNVJc59fGirAIvGXZ1gF4uBANEJS3AofreUBpLk4JeSLXEzS9UWFVhS_-zCiJs2FRndv7v-D0eAFIFyFuCab2JnbCeY64Ag&usqp=CAE",
    title: "Guitarra StratorCaster",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$2.000",
    newPrice: "$1.500",
    company: "Klass",
    color: "blue",
    category: "guitarra",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSVePQwoECQqhuJqpOIzc7sPFt_wDz0Q6FD_Etm9owv8agH9-L-fYYW6qA9kOLk_iHxyh-if_v9r6mBvJwLerox8xePFvFp-bmaodiJrNfoIJXQcTHzM9qK&usqp=CAE",
    title: "Baixo 5 cordas phx",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.400",
    newPrice: "$1.000",
    company: "PHX",
    color: "red",
    category: "baixo",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSNHi79TO4_TFkH6JzzznPp89gIJcofu--TWuH4D48KWjsbZcC_iAtXSEZvaFywc3Ia4JuJYPuQbIaGXb05DktrWUUpTpDA9dnX8TCwgbYWmW7T5XU5YUy2TA&usqp=CAE",
    title: "Baixo 4 cordas Tagima",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.200",
    newPrice: "$1.000",
    company: "Tagima",
    color: "black",
    category: "baixo",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQJFYE_7xKhRiDP_0TqkMPoh7li81YNNvc-O4FBvABuQ5wUqwYGH8Frb4rZlywxZxhvuolo-ahYBEkwRvmW4UDvEXBx-BSziVdiMgodRcw&usqp=CAE",
    title: "Baixo 5 cordas Strinberg ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.000",
    newPrice: "$800",
    company: "strinberg",
    color: "blue",
    category: "baixo",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRAYIrV3qh5rr-w5nfvIGIv-YfF-pUqUkMWrSV0jbI6LbhVSAds9rJ2Q6hdSzKcfL28B3BEtGAKMq_n7cxzFycfceY4Igdh3bZ6N6UeW3NmugVipN78zrexTg&usqp=CAE",
    title: "Baixo Tagima  Tw-65",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.400",
    newPrice: "$1.000",
    company: "Tagima",
    color: "green",
    category: "baixo",
  },

  {
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRRnGnjA8vuAleBlSAJr1uVwWXaNFCzfIm0sRNRVQMWoNX4odUdN-PxEqZ-zELLX7I4xgP6yksuq_Ab8U-bTZYx-R6cSs8Heoa4Q5ix4po3jJsr4HCGZFnYkA&usqp=CAE",
    title: "Baixo Tagima TBM4",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.400",
    newPrice: "$1.000",
    company: "Tagima",
    color: "white",
    category: "baixo",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQ4z9K63t7EVVgg4qpT9YgnrvEp9gJ5IcivMTJIUXSPLjcsbUQxf5Y9iD5y8NzHOMO1oZdJuMz4r01E6wonBXMUkW458eIy9e1fq7OwphqMjjYJwbWK6_jVXQ&usqp=CAE",
    title: "Teclado Yamaha PSR-E373",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.300",
    newPrice: "$1.200",
    company: "Yamaha",
    color: "black",
    category: "teclado",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRn12upPwS74hzkhyf_BBVq3i8BU6OAl965ox15u0gohW_jxQOKEipRwUmUUyuwGDpP-LS9jVc5MQeOPzQb3VI1Z2NM0rF4Nl9ZwWULZiE&usqp=CAE",
    title: "Teclado Roland Xps-10",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.200",
    newPrice: "$1.000",
    company: "roland",
    color: "black",
    category: "teclado",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTgbbcosTEubRZqGGB0ZhJOMDPCjT-lh7BFxVqM-oj66YLUK8Nng-8Tcg8rDRcQDnt_V_EGDcjbOY_anz0ZYqQHpQIlU2_iuTqwB--EI4o&usqp=CAE",
    title: "Teclado Yamaha PSR-S670",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.400",
    newPrice: "$1.200",
    company: "Yamaha",
    color: "black",
    category: "teclado",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQy-MP8axbwsaa8qksvL_vz7YOX2trxazxm48Pusx4sHmYAqQ2NV70jZwiOtmiSpsUweBRUS0tHw4rRMd3RdFgWIOriftgsQvCA1OkbFS1R-X4WYfH3YTmxKg&usqp=CAE",
    title: "Teclado Workstation",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.600",
    newPrice: "$1.300",
    company: "roland",
    color: "black",
    category: "teclado",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS5qIm6AOfEmE9GAVyjm9CGL-Bv6y6jBCUrsC1oA4cckMURBhEeSj3U24tQmfpkX-ib8afyAgj3B7ne5ba2AV9mno2vlwmv6lnRIWVQYKS9&usqp=CAE",
    title: "Teclado Roland XPS-30",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.300",
    newPrice: "1.100",
    company: "roland",
    color: "red",
    category: "teclado",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQx4oFA6l5IgJcn2rt-Hv6-Mn9_OdsJ8Tp7KwUpxwowRnT6oqMy2dEk6nruVrNOxBtUkwNCC6UBsD-bfr4d0HRHtwiWFKxMPxazBQmKkAV94Znlk9iFrGhfRQ&usqp=CAE",
    title: "Violão Tagima MD-25",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.400",
    newPrice: "1.000",
    company: "Tagima",
    color: "..",
    category: "guitarra",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQSo57_HeGQ8lftHOUX4Ol4BMMxgsDytuxo3H3vhK1CJNT4qvg3Uib5a3c_vPuYzlK2re0R3TrXxyhvauAlxYxP-69Lk7Q4Tua3GqVyFTGjFnStzx4_x-_B&usqp=CAE",
    title: "Violão Takamine",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.300",
    newPrice: "1.100",
    company: "Takamine",
    color: "..",
    category: "guitarra",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT5DHnHNpcXpJar1reIHPzfjmf7Azflo19g-z5xtCnIANww5bSn5cMn1u7sJ_bPV9RGHkYdV476zYCwe-6OjPd37Qvbn0R9kWfLTBR8iUMJ&usqp=CAE",
    title: "Violão Strinberg",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.300",
    newPrice: "1.200",
    company: "strinberg",
    color: "white",
    category: "guitarra",
  },

  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRgToo0rxZQij5nEUST3fNC09W-cBu0W0Gdxfjbu2x1Sa4IJjeuSzXR-2sN2HVusHRBWHIKiJusPVpg0TGZS_Ust-OiyHcbzOjeFYom-Lk9v-4EgoWegbHX&usqp=CAE",
    title: "Violão  Acustico Michael",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.200",
    newPrice: "600",
    company: "Michael",
    color: "black",
    category: "guitarra",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR8wkOoitHUSOP0aFlnKONzKXCIw6TCUC-57v7EA8DVIaYp8hBBRqWEmlO0RMjmbJunoSGgdh_1OlhrBRUCt7dcwCwE6UWaEr1V8b7eED2JL-jI88lb6tjc&usqp=CAE",
    title: "Violão Giannini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.250",
    newPrice: "$900",
    company: "Giannini",
    color: "black",
    category: "teclado",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSGchejQJNrSZnmm_xJCP9y1cweYat3_RQLFe3M4IxJSKY4MS4oxsoiIdXaLdEFC0FD4PAFlKADBSyiMPFtdv0RqTnZ9rFoz61IwVUKt6JJFD5tRT2FTGm_&usqp=CAE",
    title: "Violão Tagime Jeri",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.200",
    newPrice: "800",
    company: "Tagime",
    color: "blue",
    category: "guitarra",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRq_MDGd8jxtQ-VM-_v_l96iK08dxXNeVVjV_1-hOU_PdXebDgLaPPMvw7CLxvb5ykb_HUPJLMshmcSKbTcIl2kEzIQrfB0desn-5Vi7_D_Haal69qsyseY&usqp=CAE",
    title: "Saxofone alto latão",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.200",
    newPrice: "900",
    company: "..",
    color: "..",
    category: "..",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS9v3tYvSzbZp4ts5sObsi5IKup5R7TLzM181a03aSlQu6gAF1WdFMQOyv3hmU6pUmncy3V3ns_TfjbcxJckGppPCXXcsh92OmXj8StPg5UGxuG-iovJdn8Tw&usqp=CAE",
    title: "Saxofone Soprano",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1.400",
    newPrice: "1.000",
    company: "..",
    color: "..",
    category: "..",
  },
];

export default data;
